<script setup lang="ts">
const { locale } = useI18n()
const localePath = useLocalePath()
const siteUrl = String(useRuntimeConfig().public.siteUrl).replace(/\/+$/, '')

const copy = computed(() => locale.value === 'en' ? {
  title: 'Privacy policy', updated: 'Last updated: 10 August 2026', intro: 'This page explains which data may be processed when you use this website and why.',
  controllerTitle: 'Data controller', controller: 'Antoine Quarroz, Rue de l’Evouette 5, 1969 Saint-Martin VS, Switzerland, is responsible for processing personal data through this website. Questions concerning your data may be sent to info@antoinequarroz.ch.', controllerLink: 'Full legal information',
  dataTitle: 'Data and purposes', data: 'Depending on how you use the website, the data processed may include your name, contact details, company, project message, appointment information, contractual and billing data, IP address, browser information, request timestamps and acquisition information such as the landing page, referrer and UTM parameters. This data is used to answer requests, qualify and follow up leads in the CRM, deliver projects, manage quotes and invoices, measure website use and secure the service.',
  contactTitle: 'Contact and appointments', contact: 'Information you submit is used to answer your request, prepare a project discussion or organise an appointment. Email delivery may use Resend and appointments may open Cal.com.',
  servicesTitle: 'Service providers and recipients', services: 'Data is accessible only where needed by Antoine Quarroz and the providers used to operate the service: Infomaniak for hosting, Supabase for application data and authentication, Cloudflare Turnstile for abuse prevention, Resend for email delivery, Cal.com for appointments, Plausible for audience measurement, Google for reviews and maps, and Stripe when online payments are used. Each provider processes data under its own contractual and privacy terms.',
  analyticsTitle: 'Audience measurement and attribution', analytics: 'Plausible measures page views, outbound links, downloads and submitted forms without building an advertising profile on this website. The site also keeps landing-page, referrer and campaign parameters in the browser session so a request can be attributed to its source in the CRM.',
  googleTitle: 'Google Maps reviews', google: 'When Google reviews are enabled, the site requests live content from the Google Places API. Review author information, profile images and links are supplied by Google Maps. This content is not copied into the website database. Displaying remote Google content may establish a connection to Google.',
  googlePolicyLabel: 'Google privacy policy',
  transfersTitle: 'Processing abroad', transfers: 'Infomaniak hosts in Switzerland. Plausible hosts audience data in Germany. Supabase operates the configured project infrastructure in the European Union and may provide support from the United States. Resend and Cal.com operate from the United States. Cloudflare, Google and Stripe use global infrastructure and may process data in Switzerland, the European Economic Area, the United States and the other countries listed in their privacy and subprocessor documentation. Transfers rely, as applicable, on a Swiss adequacy decision, the Swiss–U.S. Data Privacy Framework for certified recipients, or recognised standard contractual clauses and supplementary safeguards.',
  retentionTitle: 'Retention', retention: 'Unsuccessful enquiries and CRM follow-up data are normally deleted or anonymised no later than three years after the last substantive contact. Project and contractual data is kept for the relationship and the time needed to establish or defend claims. Accounting records and supporting documents are retained for ten years from the end of the relevant financial year where Swiss law requires it. Technical logs are retained only for the period reasonably necessary for security and operation.',
  rightsTitle: 'Your rights', rights: 'Subject to applicable law, you may request access, correction, delivery or deletion of your personal data, or object to certain processing, by writing to info@antoinequarroz.ch. Identity may be verified before a request is fulfilled. Data required by law or to establish, exercise or defend legal claims may be retained. You may also contact the Swiss Federal Data Protection and Information Commissioner.',
  authorityLink: 'Swiss Federal Data Protection and Information Commissioner',
} : locale.value === 'de' ? {
  title: 'Datenschutzerklärung', updated: 'Letzte Aktualisierung: 10. August 2026', intro: 'Diese Seite erklärt, welche Daten bei der Nutzung dieser Website verarbeitet werden können und warum.',
  controllerTitle: 'Verantwortliche Person', controller: 'Antoine Quarroz, Rue de l’Evouette 5, 1969 Saint-Martin VS, Schweiz, ist für die Bearbeitung personenbezogener Daten über diese Website verantwortlich. Fragen zu Ihren Daten können an info@antoinequarroz.ch gerichtet werden.', controllerLink: 'Vollständiges Impressum',
  dataTitle: 'Daten und Zwecke', data: 'Je nach Nutzung der Website können Name, Kontaktdaten, Unternehmen, Projektanfrage, Termininformationen, Vertrags- und Rechnungsdaten, IP-Adresse, Browserangaben, Zeitstempel sowie Akquisitionsdaten wie Einstiegsseite, Referrer und UTM-Parameter bearbeitet werden. Diese Daten dienen der Beantwortung von Anfragen, der Qualifizierung und Nachverfolgung von Interessenten im CRM, der Projektabwicklung, der Verwaltung von Angeboten und Rechnungen, der Nutzungsmessung und der Sicherheit des Dienstes.',
  contactTitle: 'Kontakt und Termine', contact: 'Ihre Angaben werden verwendet, um Ihre Anfrage zu beantworten, ein Projektgespräch vorzubereiten oder einen Termin zu organisieren. Für E-Mails kann Resend und für Termine Cal.com eingesetzt werden.',
  servicesTitle: 'Dienstleister und Empfänger', services: 'Daten sind nur zugänglich, soweit dies für Antoine Quarroz und die eingesetzten Dienstleister erforderlich ist: Infomaniak für das Hosting, Supabase für Anwendungsdaten und Authentifizierung, Cloudflare Turnstile zur Missbrauchsprävention, Resend für E-Mails, Cal.com für Termine, Plausible für die Reichweitenmessung, Google für Bewertungen und Karten sowie Stripe bei Online-Zahlungen. Jeder Anbieter bearbeitet Daten gemäss seinen eigenen vertraglichen und datenschutzrechtlichen Bestimmungen.',
  analyticsTitle: 'Reichweitenmessung und Attribution', analytics: 'Plausible misst Seitenaufrufe, ausgehende Links, Downloads und übermittelte Formulare, ohne auf dieser Website ein Werbeprofil zu erstellen. Zudem speichert die Website Einstiegsseite, Referrer und Kampagnenparameter während der Browsersitzung, damit eine Anfrage im CRM ihrer Quelle zugeordnet werden kann.',
  googleTitle: 'Bewertungen von Google Maps', google: 'Wenn Google-Bewertungen aktiviert sind, ruft die Website Inhalte live über die Google Places API ab. Angaben zu Autoren, Profilbildern und Links stammen von Google Maps. Diese Inhalte werden nicht in der Website-Datenbank gespeichert. Externe Google-Inhalte können eine Verbindung zu Google herstellen.',
  googlePolicyLabel: 'Datenschutzerklärung von Google',
  transfersTitle: 'Bearbeitung im Ausland', transfers: 'Infomaniak hostet in der Schweiz. Plausible speichert Reichweitendaten in Deutschland. Supabase betreibt die konfigurierte Projektinfrastruktur in der Europäischen Union und kann Support aus den USA erbringen. Resend und Cal.com sind in den USA tätig. Cloudflare, Google und Stripe nutzen globale Infrastrukturen und können Daten in der Schweiz, im Europäischen Wirtschaftsraum, in den USA und in den weiteren Ländern bearbeiten, die in ihren Datenschutz- und Unterauftragnehmerinformationen genannt werden. Übermittlungen stützen sich je nach Fall auf einen schweizerischen Angemessenheitsbeschluss, das Swiss–U.S. Data Privacy Framework für zertifizierte Empfänger oder anerkannte Standardvertragsklauseln und ergänzende Schutzmassnahmen.',
  retentionTitle: 'Aufbewahrung', retention: 'Anfragen ohne Geschäftsbeziehung und CRM-Nachverfolgungsdaten werden grundsätzlich spätestens drei Jahre nach dem letzten wesentlichen Kontakt gelöscht oder anonymisiert. Projekt- und Vertragsdaten werden für die Dauer der Beziehung und so lange aufbewahrt, wie sie zur Geltendmachung oder Abwehr von Ansprüchen benötigt werden. Geschäftsbücher und Belege werden, soweit das Schweizer Recht dies verlangt, zehn Jahre ab Ende des betreffenden Geschäftsjahres aufbewahrt. Technische Protokolle werden nur so lange gespeichert, wie dies für Sicherheit und Betrieb angemessen erforderlich ist.',
  rightsTitle: 'Ihre Rechte', rights: 'Nach Massgabe des anwendbaren Rechts können Sie per E-Mail an info@antoinequarroz.ch Auskunft, Berichtigung, Herausgabe oder Löschung Ihrer personenbezogenen Daten verlangen oder bestimmten Bearbeitungen widersprechen. Vor der Bearbeitung kann Ihre Identität geprüft werden. Gesetzlich erforderliche Daten oder Daten zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen können aufbewahrt werden. Sie können sich auch an den Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten wenden.',
  authorityLink: 'Eidgenössischer Datenschutz- und Öffentlichkeitsbeauftragter',
} : {
  title: 'Politique de confidentialité', updated: 'Dernière mise à jour : 10 août 2026', intro: 'Cette page explique quelles données peuvent être traitées lors de votre utilisation du site et dans quel but.',
  controllerTitle: 'Responsable du traitement', controller: 'Antoine Quarroz, Rue de l’Evouette 5, 1969 Saint-Martin VS, Suisse, est responsable du traitement des données personnelles effectué au moyen de ce site. Toute question relative à vos données peut être adressée à info@antoinequarroz.ch.', controllerLink: 'Informations légales complètes',
  dataTitle: 'Données et finalités', data: 'Selon votre utilisation du site, les données traitées peuvent comprendre votre nom, vos coordonnées, votre entreprise, votre message de projet, les informations de rendez-vous, les données contractuelles et de facturation, l’adresse IP, le navigateur, l’heure des requêtes et les données d’acquisition comme la page d’arrivée, le référent et les paramètres UTM. Elles servent à répondre aux demandes, qualifier et suivre les prospects dans le CRM, réaliser les projets, gérer les devis et factures, mesurer l’utilisation du site et sécuriser le service.',
  contactTitle: 'Contact et rendez-vous', contact: 'Les informations transmises servent à répondre à votre demande, préparer un échange de projet ou organiser un rendez-vous. L’envoi des e-mails peut utiliser Resend et la prise de rendez-vous peut ouvrir Cal.com.',
  servicesTitle: 'Prestataires et destinataires', services: 'Les données sont accessibles uniquement lorsque cela est nécessaire à Antoine Quarroz et aux prestataires utilisés pour exploiter le service : Infomaniak pour l’hébergement, Supabase pour les données applicatives et l’authentification, Cloudflare Turnstile contre les abus, Resend pour les e-mails, Cal.com pour les rendez-vous, Plausible pour la mesure d’audience, Google pour les avis et cartes, et Stripe lors d’un paiement en ligne. Chaque prestataire traite les données selon ses propres engagements contractuels et de confidentialité.',
  analyticsTitle: 'Mesure d’audience et attribution', analytics: 'Plausible mesure les pages vues, les liens sortants, les téléchargements et les formulaires envoyés sans constituer de profil publicitaire sur ce site. Le site conserve aussi, pendant la session du navigateur, la page d’arrivée, le référent et les paramètres de campagne afin d’attribuer une demande à sa source dans le CRM.',
  googleTitle: 'Avis Google Maps', google: 'Lorsque les avis Google sont activés, le site récupère leur contenu en direct via l’API Google Places. Les informations d’auteur, photos de profil et liens sont fournis par Google Maps. Ces contenus ne sont pas copiés dans la base du site. Leur affichage peut établir une connexion avec Google.',
  googlePolicyLabel: 'Règles de confidentialité de Google',
  transfersTitle: 'Traitement à l’étranger', transfers: 'Infomaniak héberge en Suisse. Plausible héberge les données d’audience en Allemagne. Supabase exploite l’infrastructure du projet configuré dans l’Union européenne et peut fournir une assistance depuis les États-Unis. Resend et Cal.com opèrent depuis les États-Unis. Cloudflare, Google et Stripe utilisent des infrastructures mondiales et peuvent traiter des données en Suisse, dans l’Espace économique européen, aux États-Unis et dans les autres pays indiqués dans leurs documents de confidentialité et listes de sous-traitants. Les transferts reposent, selon le cas, sur une décision suisse d’adéquation, le Swiss–U.S. Data Privacy Framework pour les destinataires certifiés, ou des clauses contractuelles types reconnues et des garanties complémentaires.',
  retentionTitle: 'Conservation', retention: 'Les demandes sans relation commerciale et les données de suivi CRM sont normalement supprimées ou anonymisées au plus tard trois ans après le dernier échange substantiel. Les données de projet et contractuelles sont conservées pendant la relation puis le temps nécessaire à la constatation, à l’exercice ou à la défense de droits. Les livres et pièces comptables sont conservés dix ans à compter de la fin de l’exercice concerné lorsque le droit suisse l’exige. Les journaux techniques sont conservés uniquement pendant la durée raisonnablement nécessaire à la sécurité et au fonctionnement.',
  rightsTitle: 'Vos droits', rights: 'Selon le droit applicable, vous pouvez demander l’accès, la rectification, la remise ou la suppression de vos données personnelles, ou vous opposer à certains traitements, en écrivant à info@antoinequarroz.ch. Votre identité peut être vérifiée avant de traiter la demande. Les données imposées par la loi ou nécessaires à la constatation, à l’exercice ou à la défense de droits peuvent être conservées. Vous pouvez également contacter le Préposé fédéral à la protection des données et à la transparence.',
  authorityLink: 'Préposé fédéral à la protection des données et à la transparence',
})

useSeoMeta({ title: () => `${copy.value.title} — Antoine Quarroz`, description: () => copy.value.intro, robots: 'index, follow' })
useHead({ link: [
  { rel: 'canonical', href: `${siteUrl}${localePath('/confidentialite')}` },
  { rel: 'alternate', hreflang: 'fr-CH', href: `${siteUrl}/confidentialite` },
  { rel: 'alternate', hreflang: 'en-US', href: `${siteUrl}/en/confidentialite` },
  { rel: 'alternate', hreflang: 'de-CH', href: `${siteUrl}/de/confidentialite` },
  { rel: 'alternate', hreflang: 'x-default', href: `${siteUrl}/confidentialite` },
] })
</script>

<template>
  <main class="pb-24 pt-28"><article class="section-container max-w-4xl">
    <p class="text-sm font-semibold text-violet-600 dark:text-violet-300">{{ copy.updated }}</p>
    <h1 class="mt-4 font-display text-4xl font-bold text-gray-950 dark:text-white sm:text-5xl">{{ copy.title }}</h1>
    <p class="mt-6 text-lg leading-8 text-gray-600 dark:text-gray-300">{{ copy.intro }}</p>
    <div class="mt-12 space-y-10">
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.controllerTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.controller }}</p><NuxtLink :to="localePath('/mentions-legales')" class="mt-3 inline-flex min-h-11 items-center font-semibold text-violet-700 underline decoration-violet-400/60 underline-offset-4 focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 dark:text-violet-300">{{ copy.controllerLink }}</NuxtLink></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.dataTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.data }}</p></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.contactTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.contact }}</p></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.servicesTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.services }}</p></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.analyticsTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.analytics }}</p></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.googleTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.google }}</p><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" class="mt-3 inline-flex min-h-11 items-center font-semibold text-violet-700 underline decoration-violet-400/60 underline-offset-4 dark:text-violet-300">{{ copy.googlePolicyLabel }}</a></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.transfersTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.transfers }}</p></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.retentionTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.retention }}</p></section>
      <section><h2 class="font-display text-2xl font-bold text-gray-950 dark:text-white">{{ copy.rightsTitle }}</h2><p class="mt-3 leading-7 text-gray-600 dark:text-gray-300">{{ copy.rights }}</p><a href="https://www.edoeb.admin.ch/" target="_blank" rel="noopener noreferrer" class="mt-3 inline-flex min-h-11 items-center font-semibold text-violet-700 underline decoration-violet-400/60 underline-offset-4 focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 dark:text-violet-300">{{ copy.authorityLink }}</a></section>
    </div>
  </article></main>
</template>
