#import "@preview/payqr-swiss:0.4.1": swiss-qr-bill

// Shared wrapper for the invoice PDF pipeline.
// All banking and postal values must come from validated organization/client data.
#let invoice-qr-slip(
  account: none,
  creditor-name: none,
  creditor-street: none,
  creditor-postal-code: none,
  creditor-city: none,
  creditor-building: none,
  creditor-country: "CH",
  amount: none,
  currency: "CHF",
  debtor-name: none,
  debtor-street: none,
  debtor-building: none,
  debtor-postal-code: none,
  debtor-city: none,
  debtor-country: none,
  reference-type: "NON",
  reference: none,
  additional-info: none,
  language: "fr",
  standalone: false,
) = swiss-qr-bill(
  account: account,
  creditor-name: creditor-name,
  creditor-street: creditor-street,
  creditor-building: creditor-building,
  creditor-postal-code: creditor-postal-code,
  creditor-city: creditor-city,
  creditor-country: creditor-country,
  amount: amount,
  currency: currency,
  debtor-name: debtor-name,
  debtor-street: debtor-street,
  debtor-building: debtor-building,
  debtor-postal-code: debtor-postal-code,
  debtor-city: debtor-city,
  debtor-country: debtor-country,
  reference-type: reference-type,
  reference: reference,
  additional-info: additional-info,
  language: language,
  standalone: standalone,
)
